import { StyleSheet } from "react-native";
import { colors } from "./colors";

/** أنماط موحّدة لصفحات لوحة المطعم — نفس ثيم التطبيق الداكن */
export const restaurantPanel = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 16, paddingTop: 48, paddingBottom: 40 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
  topBar: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  title: { fontSize: 22, fontWeight: "700", textAlign: "right", flex: 1, color: colors.text },
  backBtn: {
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.accentOrange,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  backBtnText: { color: colors.accentOrange, fontWeight: "700" },
  hint: {
    textAlign: "right",
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  sectionTitle: {
    fontWeight: "800",
    fontSize: 16,
    textAlign: "right",
    marginBottom: 10,
    marginTop: 8,
    color: colors.text,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    backgroundColor: colors.bgCard,
    fontSize: 16,
    marginBottom: 10,
    color: colors.text,
  },
  inputMultiline: { minHeight: 72, textAlignVertical: "top" },
  btn: {
    backgroundColor: colors.accentOrange,
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    minHeight: 48,
    justifyContent: "center",
    marginTop: 8,
  },
  btnDisabled: { opacity: 0.7 },
  btnText: { color: "#FFF", fontWeight: "700", fontSize: 16 },
  card: {
    backgroundColor: colors.bgCard,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardTitle: { fontWeight: "800", textAlign: "right", fontSize: 16, color: colors.text },
  cardMeta: { textAlign: "right", color: colors.textMuted, marginTop: 4 },
  cardSub: { textAlign: "right", color: colors.textDim, fontSize: 12, marginTop: 6 },
  chip: {
    marginLeft: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 120,
  },
  chipActive: { backgroundColor: colors.accentOrange, borderColor: colors.accentOrange },
  chipText: { fontWeight: "700", textAlign: "right", color: colors.textMuted },
  chipTextActive: { color: "#FFF" },
  chipPrice: { fontSize: 12, textAlign: "right", color: colors.textDim, marginTop: 4 },
  chipPriceActive: { color: "rgba(255,255,255,0.85)" },
  quickChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.bgElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickChipText: { color: colors.accent, fontWeight: "700" },
  imagePick: {
    height: 140,
    borderRadius: 12,
    backgroundColor: colors.bgElevated,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
  },
  imagePickText: { color: colors.textMuted, fontWeight: "600" },
  editBtn: {
    backgroundColor: colors.bgElevated,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  editBtnText: { color: colors.accent, fontWeight: "700" },
  deleteBtn: {
    backgroundColor: colors.danger,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  deleteBtnText: { color: "#FFF", fontWeight: "700" },
  accentBtn: {
    backgroundColor: "#2A1F18",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accentOrange,
  },
  accentBtnText: { color: colors.accentOrange, fontWeight: "700" },
  slotChip: {
    marginLeft: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
  },
  slotChipActive: { backgroundColor: colors.accentOrange, borderColor: colors.accentOrange },
  slotChipText: { fontWeight: "600", color: colors.textMuted },
  slotChipTextActive: { color: "#FFF" },
  productRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: colors.bgCard,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  productRowOn: { borderColor: colors.accentOrange, backgroundColor: "#2A1F18" },
  productName: { fontWeight: "700", textAlign: "right", color: colors.text },
  productPrice: { fontSize: 12, color: colors.textMuted, textAlign: "right", marginTop: 2 },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.accentOrange,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnText: { color: "#FFF", fontSize: 18, fontWeight: "700" },
  qtyVal: { fontWeight: "800", minWidth: 20, textAlign: "center", color: colors.text },
  highlightBox: {
    backgroundColor: "#2A1F18",
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.accentOrange,
  },
  previewHint: { textAlign: "right", color: colors.accent, marginBottom: 8, fontWeight: "600" },
});

export const inputPlaceholderColor = colors.textDim;
